CREATE TABLE comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  body VARCHAR(140) NOT NULL,
  created_at VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_comments_post_created ON comments (post_id, created_at, id);
