CREATE TABLE follows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id INTEGER NOT NULL,
  followee_id INTEGER NOT NULL,
  created_at VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (follower_id) REFERENCES users(id),
  FOREIGN KEY (followee_id) REFERENCES users(id),
  UNIQUE (follower_id, followee_id),
  CHECK (follower_id <> followee_id)
);

CREATE INDEX idx_follows_follower ON follows (follower_id);
CREATE INDEX idx_follows_followee ON follows (followee_id);
