ALTER TABLE posts ADD COLUMN latitude DOUBLE;
ALTER TABLE posts ADD COLUMN longitude DOUBLE;
ALTER TABLE posts ADD COLUMN visibility VARCHAR(16) DEFAULT 'public' NOT NULL;

CREATE TABLE favorites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created_at VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (post_id, user_id)
);

CREATE INDEX idx_favorites_post_id ON favorites (post_id);
CREATE INDEX idx_favorites_user_id ON favorites (user_id);
